[server]
headless = true
maxUploadSize = 50

[theme]
primaryColor = "#2E4057"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[browser]
gatherUsageStats = false
